-- MySQL Script generated by MySQL Workbench
-- Mon 25 Nov 2019 10:10:06 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema null_bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema null_bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `null_bank` DEFAULT CHARACTER SET utf8 ;
USE `null_bank` ;

-- -----------------------------------------------------
-- Table `cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente` (
  `cpf_c` VARCHAR(11) NOT NULL,
  `nome_completo_c` VARCHAR(150) NOT NULL,
  `RG_c` VARCHAR(15) NOT NULL,
  `orgao_emissor_c` VARCHAR(45) NOT NULL,
  `UF_emissor_c` VARCHAR(2) NOT NULL,
  `data_nasc_c` DATE NOT NULL,
  `idade_c` INT NULL,
  `tipo_logradouro_c` VARCHAR(45) NOT NULL,
  `nome_logradouro_c` VARCHAR(150) NOT NULL,
  `numero_c` VARCHAR(4) NOT NULL,
  `bairro_c` VARCHAR(150) NOT NULL,
  `CEP_c` VARCHAR(8) NOT NULL,
  `cidade_c` VARCHAR(100) NOT NULL,
  `estado_c` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cpf_c`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `telefone` (
  `numero_ctt` VARCHAR(11) NOT NULL,
  `cliente_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`numero_ctt`, `cliente_cpf`),
  INDEX `fk_telefone_cliente_idx` (`cliente_cpf` ASC),
  CONSTRAINT `fk_telefone_cliente`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `cliente` (`cpf_c`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `email` (
  `email` VARCHAR(45) NOT NULL,
  `cliente_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`email`, `cliente_cpf`),
  INDEX `fk_email_cliente1_idx` (`cliente_cpf` ASC),
  CONSTRAINT `fk_email_cliente1`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `cliente` (`cpf_c`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencia` (
  `id_agencia` VARCHAR(4) NOT NULL,
  `nome_agencia` VARCHAR(45) NOT NULL,
  `cidade_a` VARCHAR(45) NOT NULL,
  `montante_salarial` FLOAT NULL,
  PRIMARY KEY (`id_agencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `funcionario` (
  `matricula` VARCHAR(5) NOT NULL,
  `nome_completo_f` VARCHAR(150) NOT NULL,
  `senha_f` VARCHAR(15) NOT NULL,
  `sexo_f` VARCHAR(1) NOT NULL,
  `cargo_f` VARCHAR(20) NOT NULL,
  `salario_f` FLOAT NOT NULL,
  `data_nasc_f` DATE NOT NULL,
  `idade_f` INT NOT NULL,
  `tipo_logradouro_f` VARCHAR(45) NOT NULL,
  `nome_logradouro_f` VARCHAR(150) NOT NULL,
  `numero_f` VARCHAR(4) NOT NULL,
  `bairro_f` VARCHAR(150) NOT NULL,
  `CEP_f` VARCHAR(8) NOT NULL,
  `cidade_f` VARCHAR(100) NOT NULL,
  `estado_f` VARCHAR(100) NOT NULL,
  `agencia_id_agencia` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`matricula`, `agencia_id_agencia`),
  INDEX `fk_funcionario_agencia1_idx` (`agencia_id_agencia` ASC),
  CONSTRAINT `fk_funcionario_agencia1`
    FOREIGN KEY (`agencia_id_agencia`)
    REFERENCES `agencia` (`id_agencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dependente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dependente` (
  `nome_completo_d` VARCHAR(50) NOT NULL,
  `data_nasc_d` DATE NULL,
  `idade_d` INT NULL,
  `parentesco` VARCHAR(45) NULL,
  `funcionario_matricula` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`nome_completo_d`, `funcionario_matricula`),
  INDEX `fk_dependente_funcionario1_idx` (`funcionario_matricula` ASC),
  CONSTRAINT `fk_dependente_funcionario1`
    FOREIGN KEY (`funcionario_matricula`)
    REFERENCES `funcionario` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conta` (
  `id_conta` VARCHAR(8) NOT NULL,
  `saldo` FLOAT NOT NULL,
  `senha_c` VARCHAR(10) NOT NULL,
  `gerente_matricula` VARCHAR(5) NOT NULL,
  `tipo_conta` VARCHAR(45) NOT NULL,
  `agencia_id_agencia` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`id_conta`, `agencia_id_agencia`),
  INDEX `fk_conta_agencia1_idx` (`agencia_id_agencia` ASC),
  INDEX `fk_conta_funcionario1_idx` (`gerente_matricula` ASC),
  CONSTRAINT `fk_conta_agencia1`
    FOREIGN KEY (`agencia_id_agencia`)
    REFERENCES `agencia` (`id_agencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conta_funcionario1`
    FOREIGN KEY (`gerente_matricula`)
    REFERENCES `funcionario` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poupanca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poupanca` (
  `taxa_de_juros` FLOAT NOT NULL,
  `conta_id_conta` VARCHAR(8) NOT NULL,
  `conta_agencia_id_agencia` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`conta_id_conta`, `conta_agencia_id_agencia`),
  CONSTRAINT `fk_poupanca_conta1`
    FOREIGN KEY (`conta_id_conta` , `conta_agencia_id_agencia`)
    REFERENCES `conta` (`id_conta` , `agencia_id_agencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `especial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `especial` (
  `limite_credito` FLOAT NOT NULL,
  `conta_id_conta` VARCHAR(8) NOT NULL,
  `conta_agencia_id_agencia` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`conta_id_conta`, `conta_agencia_id_agencia`),
  CONSTRAINT `fk_especial_conta1`
    FOREIGN KEY (`conta_id_conta` , `conta_agencia_id_agencia`)
    REFERENCES `conta` (`id_conta` , `agencia_id_agencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corrente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corrente` (
  `aniver_contrato` DATE NOT NULL,
  `conta_id_conta` VARCHAR(8) NOT NULL,
  `conta_agencia_id_agencia` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`conta_id_conta`, `conta_agencia_id_agencia`),
  CONSTRAINT `fk_corrente_conta1`
    FOREIGN KEY (`conta_id_conta` , `conta_agencia_id_agencia`)
    REFERENCES `conta` (`id_conta` , `agencia_id_agencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transacao` (
  `id_trasnsacao` VARCHAR(10) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `valor` FLOAT NOT NULL,
  `data_hora` DATETIME NOT NULL,
  `conta_id_conta` VARCHAR(8) NOT NULL,
  `conta_agencia_id_agencia` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`id_trasnsacao`, `conta_id_conta`, `conta_agencia_id_agencia`),
  INDEX `fk_transacao_conta1_idx` (`conta_id_conta` ASC, `conta_agencia_id_agencia` ASC),
  CONSTRAINT `fk_transacao_conta1`
    FOREIGN KEY (`conta_id_conta` , `conta_agencia_id_agencia`)
    REFERENCES `conta` (`id_conta` , `agencia_id_agencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cliente_tem_conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente_tem_conta` (
  `cliente_cpf_c` VARCHAR(11) NOT NULL,
  `conta_id_conta` VARCHAR(8) NOT NULL,
  `conta_agencia_id_agencia` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`cliente_cpf_c`, `conta_id_conta`, `conta_agencia_id_agencia`),
  INDEX `fk_cliente_has_conta_conta1_idx` (`conta_id_conta` ASC, `conta_agencia_id_agencia` ASC),
  INDEX `fk_cliente_has_conta_cliente1_idx` (`cliente_cpf_c` ASC),
  CONSTRAINT `fk_cliente_has_conta_cliente1`
    FOREIGN KEY (`cliente_cpf_c`)
    REFERENCES `cliente` (`cpf_c`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_conta_conta1`
    FOREIGN KEY (`conta_id_conta` , `conta_agencia_id_agencia`)
    REFERENCES `conta` (`id_conta` , `agencia_id_agencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
